global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;

global using ReactiveUI;
global using ReactiveUI.Wpf;
global using ReactiveUI.Fody.Helpers;

global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Documents;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using System.Windows.Navigation;
global using System.Windows.Shapes;
global using MyToDo.MVVM.ViewModels;
global using MyToDo.Wpf.Views;
global using System.Reactive.Disposables;
global using Splat;
global using static Splat.Locator;
global using System.Reflection;
global using MyToDo.MVVM;
global using MyToDo.MVVM.Common.Models;
global using DynamicData.Binding;
global using DynamicData;
global using System.Collections.ObjectModel;
global using System.Reactive.Linq;
global using MyToDo.MVVM.Extensions;